language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - tip

branches:
  only:
  - master
  - develop

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
    - os: osx

before_install:
  - make deps-test

script:
  - make test
