########################################################################################

# This Makefile generated by GoMakeGen 0.6.0 using next command:
# gomakegen .

########################################################################################

.PHONY = fmt deps-test test

########################################################################################

deps-test:
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v pkg.re/check.v1

test:
	go test -covermode=count .

fmt:
	find . -name "*.go" -exec gofmt -s -w {} \;

########################################################################################
